ktor:
  application:
    modules:
      - com.enebin.ApplicationKt.module
  deployment:
    port: 8080

  database:
    driverClassName: "org.postgresql.Driver"
    jdbcURL: "jdbc:postgresql://localhost:5432/eight_db"
    user: "eight_user"
    password: "password"
    poolSize: 10